import 'dart:io';
import 'package:path/path.dart' as p;

void main() {
  print('=== Generating Env Template ===');

  // 1. Resolve paths relative to current working directory (agent/)
  final envExampleFile = File('.env.example');
  if (!envExampleFile.existsSync()) {
    print('❌ Error: Could not find .env.example at ${envExampleFile.path}');
    exit(1);
  }

  final envExampleContent = envExampleFile.readAsStringSync().replaceAll(
    '\r\n',
    '\n',
  );

  // 2. Locate env_template.dart
  final templateFile = File(
    p.join('lib', 'core', 'setup', 'env_template.dart'),
  );

  // 3. Generate target content
  final sanitizedContent = envExampleContent.replaceAll("'''", r"\'\'\'");
  final generatedCode =
      '${'''
// This file is automatically generated. Do not edit manually.
const String defaultEnvContent = r\'\'\'$sanitizedContent\'\'\';
'''.trim()}\n';

  try {
    templateFile.createSync(recursive: true);
    templateFile.writeAsStringSync(generatedCode);
    print('✓ Successfully generated ${templateFile.path}');
  } catch (e) {
    print('❌ Error writing template file: $e');
    exit(1);
  }
}
