// Mocks generated by Mockito 5.4.6 from annotations
// in sanad_agent/test/engine/context_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sanad_agent/capabilities/models/tool_schema.dart' as _i7;
import 'package:sanad_agent/core/models/agent_response.dart' as _i2;
import 'package:sanad_agent/core/models/message.dart' as _i6;
import 'package:sanad_agent/engine/adapters/llm_adapter.dart' as _i3;
import 'package:sanad_agent/engine/adapters/llm_request_options.dart' as _i8;
import 'package:sanad_agent/interfaces/platforms/sanad_gateway/capabilities.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAgentResponse_0 extends _i1.SmartFake implements _i2.AgentResponse {
  _FakeAgentResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LLMAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockLLMAdapter extends _i1.Mock implements _i3.LLMAdapter {
  MockLLMAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int> getContextLimit([String? modelOverride]) =>
      (super.noSuchMethod(
            Invocation.method(#getContextLimit, [modelOverride]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.ModelOption>> getAvailableModels() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableModels, []),
            returnValue: _i4.Future<List<_i5.ModelOption>>.value(
              <_i5.ModelOption>[],
            ),
          )
          as _i4.Future<List<_i5.ModelOption>>);

  @override
  _i4.Future<_i2.AgentResponse> generateResponse(
    List<_i6.Message>? history, {
    List<_i7.ToolSchema>? tools,
    String? modelOverride,
    _i8.LLMRequestOptions? options = const _i8.LLMRequestOptions(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateResponse,
              [history],
              {#tools: tools, #modelOverride: modelOverride, #options: options},
            ),
            returnValue: _i4.Future<_i2.AgentResponse>.value(
              _FakeAgentResponse_0(
                this,
                Invocation.method(
                  #generateResponse,
                  [history],
                  {
                    #tools: tools,
                    #modelOverride: modelOverride,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.AgentResponse>);

  @override
  _i4.Stream<_i2.AgentResponse> generateStream(
    List<_i6.Message>? history, {
    List<_i7.ToolSchema>? tools,
    String? modelOverride,
    _i8.LLMRequestOptions? options = const _i8.LLMRequestOptions(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateStream,
              [history],
              {#tools: tools, #modelOverride: modelOverride, #options: options},
            ),
            returnValue: _i4.Stream<_i2.AgentResponse>.empty(),
          )
          as _i4.Stream<_i2.AgentResponse>);
}
